export const config = {
  botToken: process.env.TOKEN || "",
  analyticsUrl: process.env.ANALYTICS_URL || "https://6651b4300001d.tgrasp.co",
  proxyUrl: process.env.PROXY_URL || "https://api.deep.assistant.run.place",
  adminToken: process.env.ADMIN_TOKEN || "",
  keyDeepinfra: process.env.KEY_DEEPINFRA || "",
  isDev: process.env.IS_DEV === "true" || false,
  paymentsToken: process.env.PAYMENTS_TOKEN || "",
  goApiKey: process.env.GO_API_KEY || "",
  guoGuoKey: process.env.GUO_GUO_KEY || "",
  webhookEnabled: process.env.WEBHOOK_ENABLED === "true" || false,
  webhookUrl: process.env.WEBHOOK_URL || null,
  webhookPath: process.env.WEBHOOK_PATH || "/webhook",
  webhookHost: process.env.WEBHOOK_HOST || "0.0.0.0",
  webhookPort: parseInt(process.env.WEBHOOK_PORT) || 3000,
  stopEnabled: process.env.STOP_ENABLED === "true" || false,
  telegramApiId: process.env.TELEGRAM_API_ID || "",
  telegramApiHash: process.env.TELEGRAM_API_HASH || "",
  telegramPhone: process.env.TELEGRAM_PHONE || "",
  telegramBotName: process.env.TELEGRAM_BOT_NAME || "@DeepGPTBot",
  // Rate limiting configuration
  rateLimitEnabled: process.env.RATE_LIMIT_ENABLED === "true" || true,
  defaultRequestsPerMinute: parseInt(process.env.DEFAULT_REQUESTS_PER_MINUTE) || 10,
  premiumRequestsPerMinute: parseInt(process.env.PREMIUM_REQUESTS_PER_MINUTE) || 30,
  premiumEnergyThreshold: parseInt(process.env.PREMIUM_ENERGY_THRESHOLD) || 50000,
};
