name: CD - Deploy to Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT || 22 }}
        script: |
          cd ${{ secrets.DEPLOY_PATH || '/opt/telegram-bot' }}
          git pull origin main
          pip install -r requirements.txt
          # Restart the bot service
          if command -v systemctl >/dev/null 2>&1; then
            sudo systemctl restart telegram-bot || echo "Service restart failed - may need manual restart"
          elif command -v supervisorctl >/dev/null 2>&1; then
            supervisorctl restart telegram-bot || echo "Supervisor restart failed - may need manual restart"
          else
            # Kill existing process and restart
            pkill -f "__main__.py" || true
            nohup python __main__.py > bot.log 2>&1 &
            echo "Bot restarted in background"
          fi